/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Core Material-derived palette (unified across every Stitch mockup)
        'inverse-primary': '#b4c5ff',
        'secondary-container': '#d0e1fb',
        'on-primary-fixed-variant': '#003ea8',
        'primary-fixed-dim': '#b4c5ff',
        'on-secondary-fixed': '#0b1c30',
        'on-surface': '#191c1d',
        'primary-fixed': '#dbe1ff',
        'tertiary-container': '#bc4800',
        'outline-variant': '#c3c6d7',
        'on-tertiary-fixed-variant': '#7d2d00',
        'secondary-fixed-dim': '#b7c8e1',
        'inverse-surface': '#2e3132',
        'surface-container-low': '#f3f4f5',
        'on-tertiary-container': '#ffede6',
        'tertiary-fixed-dim': '#ffb596',
        'surface-container': '#edeeef',
        primary: '#004ac6',
        background: '#f8f9fa',
        error: '#ba1a1a',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#e1e3e4',
        'surface-dim': '#d9dadb',
        'surface-tint': '#0053db',
        'inverse-on-surface': '#f0f1f2',
        'surface-variant': '#e1e3e4',
        'on-background': '#191c1d',
        outline: '#737686',
        tertiary: '#943700',
        'primary-container': '#2563eb',
        'surface-bright': '#f8f9fa',
        'on-primary-container': '#eeefff',
        'on-tertiary-fixed': '#360f00',
        'on-secondary-container': '#54647a',
        'on-primary': '#ffffff',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed': '#00174b',
        'secondary-fixed': '#d3e4fe',
        'on-surface-variant': '#434655',
        'on-secondary-fixed-variant': '#38485d',
        secondary: '#505f76',
        'on-error': '#ffffff',
        surface: '#f8f9fa',
        'surface-container-high': '#e7e8e9',
        'tertiary-fixed': '#ffdbcd',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '8px',
        card: '16px',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '40px',
        'margin-mobile': '16px',
        'sidebar-width': '280px',
        'navbar-height': '64px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        gutter: '24px',
        'container-max': '1440px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        code: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'title-lg': ['18px', { lineHeight: '28px', fontWeight: '600' }],
        code: ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      boxShadow: {
        card: '0px 1px 2px 0px rgba(0,0,0,0.05)',
        'card-hover': '0px 10px 15px -3px rgba(0,0,0,0.08), 0px 4px 6px -2px rgba(0,0,0,0.03)',
      },
      transitionDuration: {
        DEFAULT: '200ms',
      },
    },
  },
  plugins: [],
}
