from typing import Any
from pydantic import BaseModel, Field


class Action(BaseModel):
    """
    Represents a tool invocation generated by the router.
    """

    tool: str = Field(
        description="Name of the tool to execute."
    )

    parameters: dict[str, Any] = Field(
        default_factory=dict,
        description="Parameters required by the selected tool."
    )